### ISSUE TITLE
ImportError: DLL load failed while importing _sherpa_onnx:

### ISSUE THREAD

**Issue by magicse** [csukuangfj/sherpa-onnx#5]
Windows.
Version 1.10.27
 File "C:\Python38\lib\site-packages\sherpa_onnx\__init__.py", line 1, in <module>
    from _sherpa_onnx import (
ImportError: DLL load failed while importing _sherpa_onnx:

**Comment by csukuangfj** [comment]
how did you install sherpa-onnx?

**Comment by magicse** [comment]
pip install sherpa_onnx.

**Comment by csukuangfj** [comment]
Have you tried to.use.a virtual environment?

**Comment by magicse** [comment]
I will try.

**Comment by magicse** [comment]
Z:\sherpa>python -m venv myenv

Z:\sherpa>myenv\Scripts\activate

(myenv) Z:\sherpa>pip install sherpa-onnx
Collecting sherpa-onnx
  Downloading sherpa_onnx-1.10.27-cp38-cp38-win_amd64.whl (20.8 MB)
     |████████████████████████████████| 20.8 MB 504 kB/s
Installing collected packages: sherpa-onnx
Successfully installed sherpa-onnx-1.10.27
WARNING: You are using pip version 20.2.1; however, version 24.2 is available.
You should consider upgrading via the 'z:\sherpa\myenv\scripts\python.exe -m pip install --upgrade pip' command.

(myenv) Z:\sherpa>python -c "import sherpa_onnx; print(sherpa_onnx.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Z:\sherpa\myenv\lib\site-packages\sherpa_onnx\__init__.py", line 1, in <module>
    from _sherpa_onnx import (
ImportError: DLL load failed while importing _sherpa_onnx: The specified module could not be found.

(myenv) Z:\sherpa>

**Comment by csukuangfj** [comment]
how many onnxruntime.dll are there on your computer?

**Comment by magicse** [comment]
C:\Python38\bin\onnxruntime.dll
C:\Python38\Lib\site-packages\onnxruntime.dll
C:\Python38\Lib\site-packages\onnxruntime\capi\onnxruntime.dll

**Comment by csukuangfj** [comment]
How did you find them?

Please delete all of them and reinstall sherpa-onnx.
